name: Deploy static content to Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to check out your repository's code
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir build3
          cp -TR build2 .
      - name: Copy files via SCP
        uses: appleboy/scp-action@v1 # Use the SCP action
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }} # Or use ssh_key and passphrase
          source: "manifest.json" # Local files/directories to transfer (comma-separated)
          target: "/var/www/u3179688/data/www/dazn311.homesstaging.online" # Target directory on the remote server
          # rm: true # Optional: Remove target directory before upload (use with caution)